### PR TITLE
add derived Copy impls for Dir, DirEntry, and File

### PR DESCRIPTION
**Pull request by jbr**
As this only adds behavior, this is semver-patch

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
I'm reluctant to derive `Copy` for these types because it means we can't add compression (#14) later on without causing breakage.

Is there a particular use case you had in mind that requires `Dir: Copy`?

**Comment by jbr** [comment]
In this case, I was mostly just surprised they weren't already Copy. I was doing a bunch of cloning to work around #73 when I ran into this.

**Comment by Michael-F-Bryan** [comment]
I'm curious why you needed to clone the `File` handles or were running into lifetime issues. Do you have any simple examples for where the lack of `'static` lifetimes causes problems?

**Comment by Michael-F-Bryan** [comment]
I'm going to close this for now seeing as it would prevent future optimisations like compression.

**Pull request closed without merging**
