### PR TITLE
Made sure the file paths are well formed

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
This fixes up the concerns raised by @arBmind in his [review comment]. It makes sure paths are correctly escaped on windows and will use the absolute path when including files with `include_bytes!()`.

[review comment]: https://github.com/Michael-F-Bryan/include_dir/commit/1ea3c6056776e0419b3da83078f1fdd1e6791898#commitcomment-24603544

### CODE REVIEW

**Comment by arBmind** [comment]
This looks very promising! Thanks 👍 
I will have to try the new code.

**Comment by arBmind** [comment]
pathes are now well formed, but still cannot be resolved.
```
include_dir("./public/")…
```
results in:
```
error: couldn't read M:\arB\Tests\rust\include_test\target\debug\build\include_test-d8d2b833f37735bb\out\./public/index.html: The system cannot find the path specified. (os error 3)
 --> M:\arB\Tests\rust\include_test\target\debug\build\include_test-d8d2b833f37735bb\out/assets.rs:6:15
  |
6 |     contents: include_bytes!(r"./public/index.html"),
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

We will need to add:
```
concat!(env!("CARGO_MANIFEST_DIR"), r"/{}")
```
This forces that all pathes are resolved relatively to the `build.rs` location. It works for me flawlessly.

**Comment by Michael-F-Bryan** [comment]
> ```rust
> concat!(env!("CARGO_MANIFEST_DIR"), r"/{}")
> ```

How would you deal with windows paths where the separator is a `\\` instead of `/`?

**Comment by arBmind** [comment]
It does not matter. Windows itself works with both separators. The Rust API is not confused as well, so it just works, at least for me so far.

**Comment by Michael-F-Bryan** [comment]
Are you sure? Adding the `env!("CARGO_MANIFEST_DIR")` makes all the integration tests fail on Linux, whereas they pass without it.

The integration tests use Python a python script to make a new crate in a temporary directory and use the `include_dir()` build script like a normal user would. Then the test itself gets used as the crate's `main.rs`, making sure it compiles executes without any errors.

**Comment by arBmind** [comment]
It seems you placed this to the call of `include_dir()`.
I meant to place it inside the `include_bytes!()` generated by the serializer.

Take a look at my [pull request](https://github.com/Michael-F-Bryan/include_dir/pull/23/files#diff-5e07616003d425b526178a965e987ce3R32) in `fn write_file`

**Comment by Michael-F-Bryan** [comment]
This [has been resolved](https://github.com/Michael-F-Bryan/include_dir/blob/2a6dab548796b3d95819389abdc2f92d0897b50f/macros/src/lib.rs#L112-L121) in #66.

**Pull request closed without merging**
